server:
  port: 8080

spring:
  datasource:
    username: lab_303305
    password: 74dd2ddfcc15_#@Aa
    url: jdbc:mysql://pc-bp18rn0tqu85a1600-public.rwlb.rds.aliyuncs.com:3306/polardb_mysql_10249gnd?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: false
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 3000
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  thymeleaf:
    prefix: classpath:/templates/
    cache:  false
    encoding: UTF-8

  resources:
    static-locations: classpath:/static/


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: hnu.houseweb.entity

